### ISSUE TITLE
Idea: Unity 2021.1 Pool Classes

### ISSUE THREAD

**Issue by schodemeiss** [IntoTheDev/Object-Pooling-for-Unity#1]
Unity 2021.1 contains some really useful classes and interfaces for creating pools. I wonder if they may be of use once 2021.1+ turns LTS?

https://docs.unity3d.com/2021.1/Documentation/ScriptReference/Pool.IObjectPool_1.html
https://docs.unity3d.com/2021.1/Documentation/ScriptReference/Pool.ObjectPool_1.html

I'd be happy to make a PR with some adapters and things down the line if that's something you'd be interested in?

**Comment by IntoTheDev** [comment]
Hello! 

I actually already looked into it and tested it a few days ago. My pool system literally is new unity pool system but with some convinient extensions methods and IPoolable interface for easy state reseting. But my system works only with GameObjects unlike the unity's one.
