### ISSUE TITLE
Request: Function to flush and clean up all cached objects from PoolContainer

### ISSUE THREAD

**Issue by mctenny** [IntoTheDev/Object-Pooling-for-Unity#2]
Thanks for this superb library!

Request a function to clean up all cached objects. The reason is the game I am working on has hundreds of enemy and environment object types, it is however in each stage only a few will be selected from the set, and rarely reuse in the next stage.
Therefore cached leftover objects will be overwhelming after the game running a prolonged period of time. It would make sense for me to have a function to cleanup all cached objects or re-init the pool.

Please kindly consider.

**Comment by IntoTheDev** [comment]
Hey!

Sorry for a late response. I'm glad that you found my library useful, I'll make clear method this week.

**Comment by IntoTheDev** [comment]
Done! You can clear any pool by calling `Clear` method on a prefab reference.

[Commit](https://github.com/IntoTheDev/Object-Pooling-for-Unity/commit/032b6af613b6f2b8fcf2f2d23a0c5b3441ef53ba)

**Comment by mctenny** [comment]
You are the best! Thank you very much indeed!
